//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int idClient { get; set; }
        public string firstName { get; set; }
        public string secondName { get; set; }
        public string lastName { get; set; }
        public string loginUserClient { get; set; }
        public string phoneNumber { get; set; }
        public string adress { get; set; }
    
        public virtual User User { get; set; }
    }
}
